from enum import Enum, auto


class OfferTagGroupEnum(str, Enum):
    Accessories = "Accessories"
    Armor = "Armor"
    Artifact = "Artifact"
    City_Resources = "City Resources"
    Consumable = "Consumable"
    Farmable = "Farmable"
    Furniture = "Furniture"
    Gathering_Gear = "Gathering Gear"
    Laborers = "Laborers"
    Luxury_Goods = "Luxury Goods"
    Magic = "Magic"
    Materials = "Materials"
    Melee = "Melee"
    Mount = "Mount"
    Off_Hand = "Off-Hand"
    Other = "Other"
    Product = "Product"
    Ranged = "Ranged"
    Resource = "Resource"
    Tomes = "Tomes"
    Token = "Token"
    Tool = "Tool"
    Trophies = "Trophies"