"""Initial revision

Revision ID: ecb42fcd8c71
Revises: 95ad87ea3c09
Create Date: 2025-05-14 22:55:42.582879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecb42fcd8c71'
down_revision: Union[str, None] = '95ad87ea3c09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers_tags',
    sa.Column('OfferId', sa.UUID(), nullable=False),
    sa.Column('TagId', sa.UUID(), nullable=True),
    sa.Column('GroupId', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['GroupId'], ['offer_tag_groups.TagGroupId'], ),
    sa.ForeignKeyConstraint(['OfferId'], ['offers.OfferId'], ),
    sa.ForeignKeyConstraint(['TagId'], ['offer_tags.TagId'], ),
    sa.PrimaryKeyConstraint('OfferId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offers_tags')
    # ### end Alembic commands ###
